name: Notarize immudb4net

on:
  push:
    branches:
      - main
      - develop

jobs:
  notarize-repository:
    name: Notarize immudb4net repository with cas and vcn
    uses: codenotary/notarize-with-cas-and-vcn/.github/workflows/notarize-with-cas-and-vcn.yml@8808d22b40dbd0257dfb456c1ab5505d1020cc54
    secrets:
      cas-api-key: ${{ secrets.CAS_API_KEY_ATTEST }}
      vcn-api-key: ${{ secrets.CICD_LEDGER1_ACTION_KEY }}
      vcn-host: ${{ secrets.CI_TEST_HOST }}
